POST  http://localhost:8080/login
Content-Type: application/json


{
    "username": "rohit@mail.com",
    "password": "rohit"
}

###

GET http://localhost:8080/products/random

###

GET http://localhost:8080/cart-items


###
GET http://localhost:8080/product-detail/6108ee0d125214237c1ad485